{OmVerDefines.inc - Omar Reis version related compiler Defines}

{$IFDEF VER130} {$DEFINE VER5UP} {$ENDIF VER130}  // Delphi 5
{$IFDEF VER140} {$DEFINE VER5UP} {$ENDIF VER140}  // Delphi 6
//futuros Delphis....
{$IFDEF VER150} {$DEFINE VER5UP} {$ENDIF VER150}  // Delphi 7
{$IFDEF VER160} {$DEFINE VER5UP} {$ENDIF VER160}  // Delphi 8
{$IFDEF VER170} {$DEFINE VER5UP} {$ENDIF VER170}  // Delphi 9
{$IFDEF VER180} {$DEFINE VER5UP} {$ENDIF VER180}  // Delphi 10



